### ISSUE TITLE
JUnit에서 @Transactional을 통한 rollback 시 auto-commit 주의사항

### ISSUE THREAD

**Issue by ksw6169** [ksw6169/toby-of-spring#3]
토비 예제로 users 테이블의 데이터를 전체 삭제하는 기능에 대해 테스트를 진행하는데, 테스트 이후에 삭제한 데이터를 다시 롤백하기 위해 `@Transactional`을 넣어줘도 롤백이 되지 않는 문제가 발생하였다.

```java
@SpringBootTest
class UserDaoTest {

    @Autowired
    private UserDao userDao;

    @Transactional
    @Test
    void deleteAll() throws SQLException {
        userDao.deleteAll();
    }
}
```

알고 보니 사용 중인 `HikariDataSource`의 `auto-commit` 값이 default : true로 설정되어 있어 이미 커밋된 데이터를 롤백하지 못한 것이었다. 아래와 같이 auto-commit 값을 설정 파일에서 false로 설정해주니 롤백이 정상적으로 동작하는 것을 확인할 수 있었다.

```yaml
spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/springbook?serverTimezone=UTC
    username: root
    password: root
    hikari:
      auto-commit: false
```
